from .homepage import *
from .product_create import *
from .product_detail import *
from .product_update import *
from .profile_create import *
from .profile_update import *
from .registration import *
from .search import *
from .signin import *
from .signout import *
from .user_cabinet import *
from .users_list import *
