# Generated by Django 5.0.6 on 2024-07-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_new_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
