# Generated by Django 5.0.6 on 2024-07-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newscategory_new_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='article',
            field=models.TextField(),
        ),
    ]
