# Generated by Django 5.0.6 on 2024-07-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumer',
            name='qty',
        ),
        migrations.AlterField(
            model_name='costumer',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
